INSERT INTO AUTH_OAUTH_REQUESTS (
  PROVIDER,
  STATE_HASH,
  NONCE_HASH,
  REDIRECT_URI,
  REDIRECT_PATH,
  MOBILE_RETURN_URI,
  EXPIRES_AT
)
VALUES (?, ?, ?, ?, ?, ?, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 10 MINUTE));
