SELECT
  ID,
  PROVIDER,
  STATE_HASH,
  NONCE_HASH,
  REDIRECT_URI,
  REDIRECT_PATH,
  MOBILE_RETURN_URI,
  EXPIRES_AT
FROM AUTH_OAUTH_REQUESTS
WHERE STATE_HASH = ?
  AND CONSUMED_AT IS NOT NULL
LIMIT 1;
