SELECT
  USERS.ID,
  USERS.EMAIL,
  USERS.NICKNAME,
  USERS.EMAIL_VERIFIED_AT,
  USERS.CREATED_AT,
  USERS.UPDATED_AT
FROM AUTH_IDENTITIES
JOIN USERS ON USERS.ID = AUTH_IDENTITIES.USER_ID
WHERE AUTH_IDENTITIES.PROVIDER = ?
  AND AUTH_IDENTITIES.PROVIDER_USER_ID = ?
LIMIT 1;
