SELECT
  USERS.ID,
  USERS.EMAIL,
  USERS.NICKNAME,
  USERS.EMAIL_VERIFIED_AT,
  USERS.CREATED_AT,
  USERS.UPDATED_AT,
  AUTH_MOBILE_OAUTH_CODES.PROVIDER
FROM AUTH_MOBILE_OAUTH_CODES
JOIN USERS ON USERS.ID = AUTH_MOBILE_OAUTH_CODES.USER_ID
WHERE AUTH_MOBILE_OAUTH_CODES.CODE_HASH = ?
  AND AUTH_MOBILE_OAUTH_CODES.CONSUMED_AT IS NOT NULL
LIMIT 1;
