SELECT
  EMAIL_VERIFICATION_CODES.ID,
  EMAIL_VERIFICATION_CODES.USER_ID,
  EMAIL_VERIFICATION_CODES.CODE_HASH
FROM EMAIL_VERIFICATION_CODES
JOIN USERS ON USERS.ID = EMAIL_VERIFICATION_CODES.USER_ID
WHERE USERS.EMAIL = ?
  AND USERS.EMAIL_VERIFIED_AT IS NULL
  AND EMAIL_VERIFICATION_CODES.USED_AT IS NULL
  AND EMAIL_VERIFICATION_CODES.EXPIRES_AT > CURRENT_TIMESTAMP
ORDER BY EMAIL_VERIFICATION_CODES.CREATED_AT DESC
LIMIT 1;
