SELECT
  PRC.ID,
  PRC.USER_ID,
  PRC.CODE_HASH
FROM PASSWORD_RESET_CODES PRC
INNER JOIN USERS U ON U.ID = PRC.USER_ID
WHERE U.EMAIL = ?
  AND PRC.USED_AT IS NULL
  AND PRC.EXPIRES_AT > CURRENT_TIMESTAMP
ORDER BY PRC.ID DESC
LIMIT 1;
