INSERT INTO QUIZ_CHAT_PROGRESS (
  USER_ID,
  CHAT_ID,
  LAST_ITEM_ID,
  LAST_QUESTION_NO
)
VALUES (
  ?,
  ?,
  ?,
  ?
)
ON DUPLICATE KEY UPDATE
  LAST_ITEM_ID = VALUES(LAST_ITEM_ID),
  LAST_QUESTION_NO = VALUES(LAST_QUESTION_NO),
  UPDATED_AT = CURRENT_TIMESTAMP;
