INSERT INTO QUIZ_WRONG_ITEMS (USER_ID, CHAT_ID, ITEM_ID, QUESTION_NO)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  UPDATED_AT = CURRENT_TIMESTAMP,
  QUESTION_NO = VALUES(QUESTION_NO),
  CHAT_ID = VALUES(CHAT_ID);
