INSERT INTO QUIZ_ITEM_ATTEMPTS (
  USER_ID,
  CHAT_ID,
  ITEM_ID,
  QUESTION_NO,
  IS_CORRECT,
  USER_ANSWER_TEXT,
  ANSWERED_DATE,
  ANSWERED_AT
)
VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  CURRENT_TIMESTAMP(3)
)
ON DUPLICATE KEY UPDATE
  CHAT_ID = VALUES(CHAT_ID),
  QUESTION_NO = VALUES(QUESTION_NO),
  IS_CORRECT = VALUES(IS_CORRECT),
  USER_ANSWER_TEXT = VALUES(USER_ANSWER_TEXT),
  ANSWERED_DATE = VALUES(ANSWERED_DATE),
  ANSWERED_AT = CURRENT_TIMESTAMP(3),
  UPDATED_AT = CURRENT_TIMESTAMP;
