SELECT
  I.ID,
  I.QUESTION_NO,
  I.QUESTION_TEXT,
  I.CREATED_AT,
  I.UPDATED_AT
FROM QUIZ_WRONG_ITEMS W
JOIN QUIZ_ITEMS I ON I.ID = W.ITEM_ID
WHERE W.USER_ID = ?
  AND W.CHAT_ID = ?
ORDER BY W.UPDATED_AT DESC, W.ID DESC;
