SELECT
  ID,
  USER_ID,
  CHAT_ID,
  MODE,
  JSON_LENGTH(MESSAGES_JSON) AS MESSAGE_COUNT,
  CREATED_AT,
  UPDATED_AT
FROM QUIZ_CHAT_LOG_SETS
WHERE USER_ID = ?
  AND CHAT_ID = ?
ORDER BY ID DESC
LIMIT 5;
