CREATE TABLE IF NOT EXISTS USERS (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  NICKNAME VARCHAR(50) NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_USERS_EMAIL (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
