CREATE TABLE IF NOT EXISTS QUIZ_CHATS (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY IDX_QUIZ_CHATS_USER_ID (USER_ID),
  CONSTRAINT FK_QUIZ_CHATS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS QUIZ_ITEMS (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CHAT_ID BIGINT UNSIGNED NOT NULL,
  QUESTION_NO INT UNSIGNED NOT NULL,
  QUESTION_TEXT TEXT NOT NULL,
  ANSWER_TEXT TEXT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_QUIZ_ITEMS_CHAT_ID_QUESTION_NO (CHAT_ID, QUESTION_NO),
  KEY IDX_QUIZ_ITEMS_CHAT_ID (CHAT_ID),
  CONSTRAINT FK_QUIZ_ITEMS_CHAT_ID FOREIGN KEY (CHAT_ID) REFERENCES QUIZ_CHATS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
