CREATE TABLE IF NOT EXISTS QUIZ_CHAT_PROGRESS (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  CHAT_ID BIGINT UNSIGNED NOT NULL,
  LAST_ITEM_ID BIGINT UNSIGNED NULL,
  LAST_QUESTION_NO INT UNSIGNED NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_QUIZ_CHAT_PROGRESS_USER_CHAT (USER_ID, CHAT_ID),
  KEY IDX_QUIZ_CHAT_PROGRESS_CHAT_ID (CHAT_ID),
  CONSTRAINT FK_QUIZ_CHAT_PROGRESS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_QUIZ_CHAT_PROGRESS_CHAT_ID FOREIGN KEY (CHAT_ID) REFERENCES QUIZ_CHATS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
