CREATE TABLE IF NOT EXISTS QUIZ_ITEM_ATTEMPTS (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  CHAT_ID BIGINT UNSIGNED NOT NULL,
  ITEM_ID BIGINT UNSIGNED NOT NULL,
  QUESTION_NO INT UNSIGNED NOT NULL,
  IS_CORRECT BOOLEAN NOT NULL,
  ANSWERED_DATE DATE NOT NULL,
  ANSWERED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_QUIZ_ITEM_ATTEMPTS_USER_ITEM (USER_ID, ITEM_ID),
  KEY IDX_QUIZ_ITEM_ATTEMPTS_USER_DATE (USER_ID, ANSWERED_DATE),
  KEY IDX_QUIZ_ITEM_ATTEMPTS_CHAT_ID (CHAT_ID),
  CONSTRAINT FK_QUIZ_ITEM_ATTEMPTS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_QUIZ_ITEM_ATTEMPTS_CHAT_ID FOREIGN KEY (CHAT_ID) REFERENCES QUIZ_CHATS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_QUIZ_ITEM_ATTEMPTS_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES QUIZ_ITEMS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
