-- 정책 테이블
CREATE TABLE IF NOT EXISTS POLICY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONTENT MEDIUMTEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
