CREATE TABLE IF NOT EXISTS QUIZ_CHAT_LOG_SETS (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  CHAT_ID BIGINT UNSIGNED NOT NULL,
  MODE VARCHAR(20) NOT NULL,
  MESSAGES_JSON JSON NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY IDX_QUIZ_CHAT_LOG_SETS_USER_CHAT (USER_ID, CHAT_ID),
  KEY IDX_QUIZ_CHAT_LOG_SETS_USER_CHAT_MODE (USER_ID, CHAT_ID, MODE),
  CONSTRAINT FK_QUIZ_CHAT_LOG_SETS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_QUIZ_CHAT_LOG_SETS_CHAT_ID FOREIGN KEY (CHAT_ID) REFERENCES QUIZ_CHATS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
