ALTER TABLE USERS
  DROP INDEX UQ_USERS_COGNITO_SUB,
  DROP COLUMN COGNITO_SUB,
  MODIFY EMAIL VARCHAR(255) NOT NULL,
  ADD COLUMN PASSWORD_HASH VARCHAR(255) NULL AFTER EMAIL,
  ADD UNIQUE KEY UQ_USERS_EMAIL (EMAIL);
