CREATE TABLE IF NOT EXISTS PASSWORD_RESET_CODES (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  CODE_HASH VARCHAR(255) NOT NULL,
  EXPIRES_AT TIMESTAMP NOT NULL,
  USED_AT TIMESTAMP NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY IDX_PASSWORD_RESET_CODES_USER (USER_ID),
  KEY IDX_PASSWORD_RESET_CODES_EXPIRES (EXPIRES_AT),
  CONSTRAINT FK_PASSWORD_RESET_CODES_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (ID)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
