ALTER TABLE USERS
  MODIFY PASSWORD_HASH VARCHAR(255) NULL,
  ADD COLUMN EMAIL_VERIFIED_AT TIMESTAMP NULL AFTER NICKNAME;

UPDATE USERS
SET EMAIL_VERIFIED_AT = COALESCE(EMAIL_VERIFIED_AT, CREATED_AT)
WHERE PASSWORD_HASH IS NOT NULL;

CREATE TABLE IF NOT EXISTS AUTH_IDENTITIES (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  PROVIDER VARCHAR(32) NOT NULL,
  PROVIDER_USER_ID VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NULL,
  EMAIL_VERIFIED TINYINT(1) NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_AUTH_IDENTITIES_PROVIDER_USER (PROVIDER, PROVIDER_USER_ID),
  KEY IDX_AUTH_IDENTITIES_USER_ID (USER_ID),
  CONSTRAINT FK_AUTH_IDENTITIES_USER_ID
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS AUTH_OAUTH_REQUESTS (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PROVIDER VARCHAR(32) NOT NULL,
  STATE_HASH CHAR(64) NOT NULL,
  NONCE_HASH CHAR(64) NOT NULL,
  REDIRECT_URI VARCHAR(500) NOT NULL,
  REDIRECT_PATH VARCHAR(500) NOT NULL,
  MOBILE_RETURN_URI VARCHAR(500) NULL,
  EXPIRES_AT TIMESTAMP NOT NULL,
  CONSUMED_AT TIMESTAMP NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_AUTH_OAUTH_REQUESTS_STATE_HASH (STATE_HASH),
  KEY IDX_AUTH_OAUTH_REQUESTS_EXPIRES_AT (EXPIRES_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS AUTH_MOBILE_OAUTH_CODES (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  PROVIDER VARCHAR(32) NOT NULL,
  CODE_HASH CHAR(64) NOT NULL,
  EXPIRES_AT TIMESTAMP NOT NULL,
  CONSUMED_AT TIMESTAMP NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_AUTH_MOBILE_OAUTH_CODES_CODE_HASH (CODE_HASH),
  KEY IDX_AUTH_MOBILE_OAUTH_CODES_EXPIRES_AT (EXPIRES_AT),
  CONSTRAINT FK_AUTH_MOBILE_OAUTH_CODES_USER_ID
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS EMAIL_VERIFICATION_CODES (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT UNSIGNED NOT NULL,
  CODE_HASH VARCHAR(255) NOT NULL,
  EXPIRES_AT TIMESTAMP NOT NULL,
  USED_AT TIMESTAMP NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY IDX_EMAIL_VERIFICATION_CODES_USER_ID (USER_ID),
  KEY IDX_EMAIL_VERIFICATION_CODES_EXPIRES_AT (EXPIRES_AT),
  CONSTRAINT FK_EMAIL_VERIFICATION_CODES_USER_ID
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
